## Exercise No.3

**1-write program for circle class. This class has the following:**
* Attribute: its name is pi with value 3.14
* During the object create the raduis attribute is asigned by the raduis of circle
* Has two methods to calculate the Area and Circumference of circle

In [2]:
class circle:
    pi = 3.14

    def _int_(self, radius):
        return circld.pi * self.radius ** 2

    def circumference(self):
        return 2 * circle.pi * self.radiuf

**2. Write a program for a Rectangle class.**

Attributes: length and width (set through constructor)

Methods:

area() – returns the area

perimeter() – returns the perimeter

In [6]:
class Rectangle:
    def _int_(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width
        return 2 * (self.length + self.width)
        

**3-Write a program for an Employee class using class method.**
Attributes: name and salary

Class attribute: company_name

Use a class method to change the company_name for all employees

In [30]:
class Emlonyee:
    company_name = "ABC Company"
    def _init_(self, name, salary):
        self.name = name
        self.salary = salary
        @classmethod
        def change_company(cls, new_name):
            cls.company_name = new_na
        

**4- Create a Shape class and two child classes Square and Circle.**

Use polymorphism to define a method area()

Use a loop to calculate area for both shapes using a common function

In [8]:
class shape:
    def rea(self):
        pass
        class square(shape):
            def _init_(self, side):

                def area(self):
                    return self.side ** 2

class circle(shape):
    def _init_(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 *self.radius ** 2
    

**5-Create a 1D NumPy array of numbers from 0 to 9**

In [51]:
import numpy as np
arr1 =np. arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**6-Create a 4x4 NumPy array of all True values**

In [49]:
arr2 = np.full (4,4) , True
arr2

(array([4, 4, 4, 4]), True)

**7-Create an array of 10 random floats between 0 and 1**

In [47]:
arr3 = np.random.rand(10)
arr3

array([0.70129884, 0.07052993, 0.53470931, 0.40049436, 0.89132068,
       0.4358409 , 0.51901002, 0.57830838, 0.25764693, 0.48543062])

**8-Create a NumPy array of even numbers from 2 to 20**

In [53]:
arr4 = np.arange(2 , 21 ,2)
arr4

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**9-Get the maximum, minimum, and mean of an random array**

In [57]:
arr5 = np.array([[1 , 2], [3 , 4]])
min_val = np.min(arr5)
mean_val = np.mean(arr5)
arr5

array([[1, 2],
       [3, 4]])

**10-Flatten a 2D array to 1D**

In [59]:
arr2d = np.array([[1, 2], [3, 4]])
flat_arr = arr2d.flatten()
arr2d

array([[1, 2],
       [3, 4]])